### ISSUE TITLE
 about UAV_correct_human.py

### ISSUE THREAD

**Issue by yygbruce** [asu-iris/Safe-MPC-Alignment#1]
Hello, @Zhi-Xian-Xie ! When i run the file(UAV_correct_human.py), the following error occurs:
Traceback (most recent call last):
  File "UAV_correct_human.py", line 17, in <module>
    from utils.RBF import rbf
ImportError: cannot import name 'rbf' from 'utils.RBF' (Safe-MPC-Alignment/utils/RBF.py)

In the file(RBF.py), i don't find the function(rbf).

**Comment by Zhi-Xian-Xie** [comment]
Sorry for your inconvenience, files named UAV_correct_human.py and all versions of UAV_correct_human_x.py are legacies in development, thus they may not be working. I have deleted them in the code, and you can just run UAV_correct_human_mj_v3.py. Also, line 30 needs to be commented and I have fixed it in the latest commit.

**Comment by yygbruce** [comment]
Ok, thank you!
